### ISSUE TITLE
170906 똔두니

### ISSUE THREAD

**Issue by bloojun** [bloojun/bloojun#11]
**큐의 종류에 대해 Issue 란에 쓰고 정리**

 큐는 선입선출 ! 먼저 들어온게 먼저 나가는 구조이다. 삽입이 일어나는곳을 rear, 삭제가 일어나는 곳을 front라 칭한다. 큐는 배열과 연결리스트로 구현가능하다.
 배열 큐로는 선형큐와 원형 큐가 있다.  첫번째로 선형큐는 1차원 배열을 사용하는데 front는 첫 번째를 가리키고 rear는 마지막을 가리킨다. 삽입을 하면서 rear가 1씩 증가하고 front도 배열을 1씩 이동하면서 front가 가리키는 곳의 값을 삭제시킨다.  1씩계속 이동하면서 배열의 앞부분이 비게되므로 공간을 사용못한다. 그래서 남아있는 값들을 다시 배열의 앞부분으로 땡겨주어야 하는 일이 생긴다. 허나 이 작업을 매번 해주어야하므로 시간도 더 걸리게되고 코딩도 복잡해진다. 
 두번째로는 원형큐가 있다. 원형 큐는 원래직선이었던 큐가 원형으로 말아져있다고 생각하면된다. 배열의 시작점과 배열의 마지막쪽이 연결되어있다고 생각하면된다.  
 연결리스트로 구현된 큐는 배열보다는 크기가 제한적이지 않다는 장점이 있지만 코드가 더 복잡해진다. 단순 연결리스트에 front와 rear의 포인터를 추가해 만든다.  삽입 할때에는 연결리스트의 끝에 새로운 노드를 이어붙이면 된다. 삭제 할때에는 front가 가리키던 노드의 값을 빼내고 다음연결리스트의 노드를 가리키면 된다. 그런다음 노드를 삭제하면 된다링.
마지막으로 덱이 있는데 front와 rear에서 삽입삭제(넣뻏)가 가능하다. 덱은 스택과 큐의 방식을 다 이용한다. 이중 연결리스트로 구현해야 편리하다. 
책을 보고 원리는 이해했고 배열로는 충분히 혼자 잘 짤수 있을것 같다링.
덱을 짜려면 연결리스트를 해봐야 할 것같다. 그리고 포인터에 대한 공부도 더 필요한 것 같다.

**Comment by warguss** [comment]
가독성있게 다시써라. 밑빠진독 깨버리기전에

**Comment by forever9882** [comment]
close
