### ISSUE TITLE
큐 정리. 170908 수정했쑵니다

### ISSUE THREAD

**Issue by bloojun** [bloojun/bloojun#14]
큐의 종류에 대해 Issue 란에 쓰고 정리

**큐**
선입선출(먼저 들어온게 먼저 나가는)  구조이다. 
삽입이 일어나는곳 후단을 rear, 삭제가 일어나는 곳을 전던을 front라 칭한다.
큐는 배열과 연결리스트로 구현가능하다.

**선형큐**
1차원 배열을 사용.
배열의 앞 부분이 비어 있어도 쓰지를 못하여 모든 요소들을 앞쪽으로 땡겨야함
매번 이동시켜야 하므로 비효율적이다.

**원형큐**
선형큐의 문제점을 보완하기 위해 나옴.
배열의 시작점과 배열의 마지막쪽이 연결되어있다고 생각하면된다.
공백 상태와 포화 상태를 쉽게 구분하기 위해서 자리 하나를 항상 비워둔다.

**연결리스트로 구현된 큐**
배열보다는 크기가 제한적이지 않지만 코드가 더 복잡.
단순 연결리스트에 front와 rear의 포인터를 추가해 만든다.

**우선순위 큐**
데이터들이 우선순위를 가지고 있고 우선순위가 높은 데이터가 먼저 나간다.
주로 힙을 이용하여 구현한다.
네트워크 트래픽 제어, 운영 체제에서의 작업 스케쥴링등에 사용된다.

**덱**
전단과 후단에서 모두 삽입삭제가 가능하다.
스택과 큐의 방식을 다 이용한다. 

------------------------------------------------------------------------------------------------------------
170908 추가 수정
**이중연결리스트로 구현된 큐**
순방향뿐만 아니라 역방향으로도 검색이 가능함. 
앞에서 처음 노드는 front 포인터가 가리키고 마지막 노드는 rear 포인터가 가리키도록 연결한다. 
양방향이 가능해 탐색속도를 향상시킬 수 있다.

**Comment by warguss** [comment]
이중큐 추가 조사

**Comment by bloojun** [comment]
이중연결리스트로 구현된 큐
순방향뿐만 아니라 역방향으로도 검색이 가능함. 
앞에서 처음 노드는 front 포인터가 가리키고 마지막 노드는 rear 포인터가 가리키도록 연결한다. 
양방향이 가능해 탐색속도를 향상시킬 수 있다.
