### ISSUE TITLE
컨플릭트

### ISSUE THREAD

**Issue by bloojun** [bloojun/bloojun#16]
실수
master에서 Stack.c를 푸시하고 브랜치 cheongjun 에서도 같은파일을 푸시하는 바람에 충돌이 발생했다. 
컨플릭트가 발생할 때 마지막에 푸시를 한 이용자가 컨플릭트 책임을 위임받는다.
그래서 브랜치 cheongjun쪽에서 컨플릭트가 발생하였다.

**컨플릭트**
브랜치를 나누고 각자 작업할 때 같은 부분을 수정하면 발생한다.
이때 버전관리 시스템이 자동으로 병합해줄 수 없다고 판단하여 해결을 사용자에게 위임한다.
비커즈, 한 브랜치의 소스만 쓸 껀지 두 수정부분을 합쳐서 쓸껀지 판단할 수 없기 때문.
컨플릭트의 발생을 예방하려면 자주 병합을 시켜줘야 한다.

**Comment by warguss** [comment]
master <- cheongjun 으로 병합하여도, local의 stage까지만 올라간 상태라서 아무문제없음.

하지만, push 까지 자동으로해주는 툴을 쓰는바람에 그게 적용이 된거임. 
한번더 실수하면 그냥 bash로간다
